### ISSUE TITLE
CSS样式超出内容用省略号显示

### ISSUE THREAD

**Issue by mochengtu** [mochengtu/rollupkit#4]
```css
/* 超出一行用省略号显示 */
.title{
  overflow:hidden;
  white-space:nowrap;
  text-overflow:ellipsis;
}
/* 超出2行用省略号显示 */
.title{
  overflow:hidden;
  display:-webkit-box;
  -webkit-line-clamp:2;
  -webkit-box-orient:vertical;
  text-overflow:ellipsis;
}
```
